Finschia/finschia

CHANGELOG.md, RELEASE_NOTE.md
* Rename and bump up dependencies
* rename the following dependencies (and update scripts when necessary)
* github.com/line/lbm-sdk => github.com/Finschia/finschia-sdk
* github.com/line/ostracon => github.com/Finschia/ostracon
* github.com/line/ibc-go => github.com/Finschia/ibc-go
* github.com/line/wasmd => github.com/Finschia/wasmd
* bump up Finschia/finschia-sdk
* chore: change import path to github.com/Finschia/finschia-sdk
fix: not to throw error when no txs in block
refactor: refactor x/token,collection query errors
* change the ci runners from self-hosted to ubuntu-latest
=> chore: Release v1.0.0-rc6

CHANGELOG.md, go.mod, go.sum
Refer:
- Finschia/finschia-sdk#984
=> Bump github.com/Finschia/finschia-sdk from v0.47.0-rc6 to v0.47.0-rc7

CHANGELOG.md, RELEASE_NOTE.md
* Bump finschia-sdk from v0.47.0-rc6 to v0.47.0-rc7
* fix state breaking change problem of v1.0.0-rc5
=> chore: Release v1.0.0-rc7

CHANGELOG.md, Makefile
closes: #186 
fix the wrong app name in the `fnsad` cli example. (`finschia` -> `fnsad`)
execute `./build/fnsad tx gov submit-proposal community-pool-spend --help` command, and then you can find the fixed app name in example.
=> fix: example wrong app name in `--help` description of cli

CHANGELOG.md, Dockerfile
change `from` image to golang:1.18-alpine
Chain killed with error below when wasm's `store` tx run.
I run finschia-js tests with docker image build from this branch and all tests were passed.
2023/05/31-04:31:24.867 INF Timed out dur=300 height=5 module=consensus round=0 step=3
SIGABRT: abort
PC=0x400084a22d m=11 sigcode=18446744073709551610
signal arrived during cgo execution
goroutine 148 [syscall]:
runtime.cgocall(0x1c8abd0, 0xc0054801d0)
runtime/cgocall.go:157 +0x5c fp=0xc005480190 sp=0xc005480158 pc=0x59f79c
github.com/Finschia/wasmvm/internal/api._C2func_save_wasm(0x40284af030, {0x0, 0xc00554a000, 0x34ce7}, 0xc0053fe380)
_cgo_gotypes.go:625 +0x69 fp=0xc0054801d0 sp=0xc005480190 pc=0x1b5bee9
github.com/Finschia/wasmvm/internal/api.Create.func1({0x0?}, {0x0?, 0xc00554a000?, 0xc0054802a …
=> fix wasm error by changing `from` image to golang:1.18-alpine

CHANGELOG.md, go.mod, go.sum
bump up ibc-go from v3.3.3 to v3.3.4-0.20230531095546-59c47ab8e095, because [the security issue](https://github.com/Finschia/ibc-go/pull/14) of `Handle ordered packets in UnreceivedPackets query`( Finschia/ibc-go#15 )
Reported ibc-go's sercurity vulnerability, [IBC Security Advisory Huckleberry](https://forum.cosmos.network/t/ibc-security-advisory-huckleberry/10731/1)
=> feat: bump up ibc-go from v3.3.3 to v3.3.4-0.20230531095546-59c47ab8e095

CHANGELOG.md, Dockerfile
Fixes #208
This error occurs because `fnsad` binary is not a binary to use a complete static libraries.
=> fix: the cgo calling error of libwasmvm on docker image

CHANGELOG.md, app/app.go, cli_test/cli_test.go, cli_test/test_helpers.go
closes: #215 
Add have wasmplus gov proposal command in `fnsad` cli. `activate-contract`, `deactivate-contract`.
There are not `activate-contract` and `deactivate-contract` gov command in `fnsad` cli of finschia v1.0.0.
```
$ fnsad tx gov submit-proposal deactivate-contract
Error: accepts 1 arg(s), received 0
Usage:
fnsad tx gov submit-proposal deactivate-contract [contract_addr_bech32] [flags]
….
```
```
$ fnsad tx gov submit-proposal activate-contract 
Error: accepts 1 arg(s), received 0
Usage:
fnsad tx gov submit-proposal activate-contract [contract_addr_bech32] [flags]
…..
```
=> fix: add wasmplus proposal command in `fnsad` cli

CHANGELOG.md, Makefile
I made a bug in #221. Fix this.
The `fnsad` binary will not be built if there are multiple `build_tags`.
=> fix: compile error when the `build_tags` is multiple.

CHANGELOG.md, RELEASE_CHANGELOG.md, RELEASE_NOTE.md, go.mod, go.sum
This version base on [finschia-sdk v0.47.2](https://github.com/Finschia/finschia-sdk/releases/tag/v0.47.2), [Ostracon v1.1.0](https://github.com/Finschia/ostracon/tree/v1.1.0), [finschia/wasmd v0.1.3](https://github.com/Finschia/wasmd/releases/tag/v0.1.3) and [finschia/ibc-go v3.3.3](https://github.com/Finschia/ibc-go/releases/tag/v3.3.3).
* (build) [\#218](https://github.com/Finschia/finschia/pull/218) bump up finschia-sdk from v0.47.0 to v0.47.1-rc2
* (build) [\#216](https://github.com/Finschia/finschia/pull/216) fix the cgo calling error of libwasmvm on docker image
* (x/wasm) [\#217](https://github.com/Finschia/finschia/pull/217) add wasmplus proposal command in fnsad cli
=> Release finschia v1.1.0

.github/workflows/tests.yml, .gitignore, .gitmodules, CHANGELOG.md, Makefile
Remove unused shared library 
* libsodium
* libsecp256k1
The `libsodium` vrf library doesn't need any more through https://github.com/Finschia/ostracon/pull/652.
So I remove it for preparing single binaries on macos. This is related with #231.
To build single binary, there should be no dynamic library except `cleveldb`.
Ostracon does not use the `libsodium` vrf library and it changed to `curve25519-voi`. So `libsodium` submodule and build scripts are not need any more. And I need this remove any dynamic libraries or change to static libraries for building single binary on macos. So I need to remove libsodium first.
=> feat!: remove `libsodium` vrf library.

CHANGELOG.md, cmd/fnsad/cmd/root.go
This patch would revert fdd41c1098ce8654ee7ff22fef2277b242f99110 in #243 in order to restore wasm config.
=> fix: revert removing wasm configs

CHANGELOG.md, go.mod, go.sum
* Apply the bug fix of wasmd
* https://github.com/Finschia/wasmd/pull/85
=> deps: bump up wasmd from 516eaaec to c581a5f2

.github/workflows/ci-smart-contract.yml, CHANGELOG.md, Makefile
When building with `make build`, change the default build method so that it is built as a binary that uses a shared library.
However, we can build a single binary as a static library using the command `make build LINK_STATICALLY=true`.
closes: #276 
A single binary build using static library failed in Ubuntu. 
And there is not fix way because wasmvm static library use mucl static library.
1. `make build` 
2. check the build binary in the `./build/` directory
3. check linked libraries as using `ldd ./build/fnsad`.
```shell
$ ldd ./build/fnsad 
linux-vdso.so.1 (0x00007fff68001000)
libwasmvm.x86_64.so => /home/zemyblue/go/pkg/mod/github.com/!finschia/wasmvm@v1.1.1-0.11.4-rc1/internal/api/libwasmvm.x86_64.so (0x00007f904b800000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 …
```
=> build: change to the default build method that uses a shared library

CHANGELOG.md, docs/finschia-tutorials/installation.md
* Add optional guide for static build
=> docs: add guide for static build

CHANGELOG.md, Makefile
closes: #XXXX
`wget` is not a default tool on MacOS
=> build: use curl instead of wget on MacOS

CHANGELOG.md, RELEASE_CHANGELOG.md, RELEASE_NOTE.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml
This version base on [finschia-sdk v0.48.0](https://github.com/Finschia/finschia-sdk/releases/tag/v0.48.0), [Ostracon v1.1.2](https://github.com/Finschia/ostracon/tree/v1.1.2), [finschia/wasmd v0.2.0](https://github.com/Finschia/wasmd/releases/tag/v0.2.0) and [finschia/ibc-go v4.3.1](https://github.com/Finschia/ibc-go/releases/tag/v4.3.1).
* (finschia-sdk) Bump github.com/Finschia/finschia-sdk from v0.47.0 to v0.48.0
* (feat) [\#243](https://github.com/Finschia/finschia/pull/243) Bump github.com/Finschia/finschia-sdk from v0.47.0 to v0.47.1-rc1
* (feat) [\#255](https://github.com/Finschia/finschia/pull/255) Bump up finschia-sdk from v0.48.0-rc1 to da331c01fa
* (feat) [\#262](https://github.com/Finschia/finschia/pull/262) Bump up finschia-sdk from v0.48.0-rc2 to `0a27aef22921` and bump up …
=> Release finschia v2.0.0

.github/CODEOWNERS, .mergify.yml, CHANGELOG.md
closes: #XXXX
* Set up a code owner to take responsibility for this repository
* Set a backport action -> Decide to use mixed Git branching strategy([GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) + [GitLab Flow](https://about.gitlab.com/blog/2023/07/27/gitlab-flow-duo/))
=> chore: set CODEOWNERS & backport action

CHANGELOG.md, RELEASE_CHANGELOG.md, RELEASE_NOTE.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml
This version base on [finschia-sdk v0.48.1](https://github.com/Finschia/finschia-sdk/releases/tag/v0.48.1), [Ostracon v1.1.2](https://github.com/Finschia/ostracon/tree/v1.1.2), [finschia/wasmd v0.2.0](https://github.com/Finschia/wasmd/releases/tag/v0.2.0) and [finschia/ibc-go v4.3.1](https://github.com/Finschia/ibc-go/releases/tag/v4.3.1).
* (improvements) #230
* (chore) #300
* (finschia-sdk) #298
* (ci) #290
* (ci) #291
=> Release finschia v2.0.1

CHANGELOG.md, Dockerfile, networks/local/finschianode/Dockerfile
This PR fix the build error that occurs after bumping up the Go version from 1.18 to 1.20, caused by #241  
Without this PR, we cannot build a Docker image of Finschia.
The reason is golang:1.20-alpine is using alpine3.19, while alpine3.19 upgraded the libc version which includes the following PR: https://github.com/rust-lang/libc/pull/2935
So, this PR changes the Docker image version and sets it to golang:1.20-alpine3.17.
closes: #314 
You can try ```make docker-build ARCH=arm64``` or ```make docker-build``` to build docker image locally.
=> fix: change docker image version to fix build error

CHANGELOG.md, ante/ante_test.go, app/app.go, app/encoding.go, app/helpers/test_helpers.go, cli_test/cli_test.go, cli_test/multi_test.go, cli_test/test_helpers.go, cmd/fnsad/cmd/root.go, cmd/fnsad/cmd/testnet_test.go, cmd/fnsad/main.go, go.mod, interchaintest/go.mod
* Rename namespace to v3
* change the upgradename to `v3-Rose`
=> chore: rename namespace to v3

CHANGELOG.md, Makefile
This patch sets Finschia/ostracon version information.
Equivalent of Finschia/finschia-sdk#1298.
1. `make build`
2. `./build/fnsad ostracon version`
=> build: set Finschia/ostracon version

.mergify.yml, CHANGELOG.md, app/app.go, go.mod, go.sum
closes: #XXXX
* Add fswap module
* Add fbridge module
=> build(deps): bump `finschia-sdk` v0.48.1 to v0.49.0-rc1

.golangci.yml, CHANGELOG.md, app/helpers/test_helpers.go, cli_test/test_helpers.go
closes: #XXXX
* maligned -> govet
* varcheck, structcheck, deadcode -> unused
* golint -> revive
* scopelint -> exportloopref
=> style: replace deprecated linters with new ones

CHANGELOG.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml
* add fswap and fbridge swagger settings in swagger config 
* The queries of fswap and fbridge module are not displayed in swagger. 
1. make install
2. set default single node setting. `./init_single.sh`
3. change app.toml setting for enable swagger.  `enable` and `swagger` of `[api]` section set `true`.
4. `fnsad start`
5. view http://localhost:1317/swagger/
=> chore: add fswap and fbridge swagger settings in swagger config

CHANGELOG.md, RELEASE_DESCR.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml
* (fswap, fbridge) #354
* (fbridge) #356
* (build) #358
* (fswap, fbridge) #360
* (fswap, fbridge) #367
* (fswap) #368
* (fswap, fbridge) #374
* (fswap) #379
* (fswap, fbridge) #381
* (app) #352
* (build) #340
* (ci) #363
* (ci) #364
* (swagger) #372
=> Release Finschia v4.0.0

CHANGELOG.md, RELEASE_DESCR.md, scripts/release-note.py
closes: #XXXX
* Force user to write `RELEASE_DESCR` and `CHANGELOG` for all tags from now. We allowed to not write those sections sometimes and worked as best effort (getting latest previous content instead of exact previous tag content if we can't find). I decided to apply this rule to avoid confusion during release process.
* small improvement - allowing version suffix in package path.
=> feat: Force user to follow the rule of release note generation

CHANGELOG.md, Makefile
* Modify the way the binary version is set when compiling.
* if main branch, `main-f71e2e77b45e64df1ae8790b61f80b192350d688`.
* if feat/compile_with_tags branch, `feat_compile_with_tags-726c33ee7d7aad03cc4c705c97acbffc67b39bd4`.
* if v4.0.0 tag commit, `v4.0.0`
When compiled with the following command, v4.0.0 is not output.
```
git clone https://github.com/Finschia/finschia
cd finschia && git checkout v4.0.0
make install
fnsad version
```
=> chore: Modify the way the binary version is set when compiling
