Finschia/finschia

.github/workflows/release-build.yml, CHANGELOG.md
Add the ci for darwin build in release tag assets.
=> ci: add a ci to build darwin version when add tag

.github/workflows/lint.yml, .github/workflows/sims.yml, .github/workflows/tag.yml, CHANGELOG.md
=> ci: update tag github action

CHANGELOG.md, app/app.go, go.mod, go.sum
Refer:
- Finschia/finschia-sdk#999
=> feat!: apply Finschia/finschia-sdk#999

.github/dependabot.yml, CHANGELOG.md
Add `dependabot` github action for checking security issue of dependence libraries.
=> ci: add dependabot github action

CHANGELOG.md, go.mod, go.sum
Bump up Finschia/wasmd from v0.1.3 to v0.1.4
- fix: stop wrap twice the response of handling non-plus wasm message in plus handler by @loloicci in https://github.com/Finschia/wasmd/pull/35
- chore: update notice by @zemyblue in https://github.com/Finschia/wasmd/pull/44
- fix: delete unnecessary test by @da1suk8 in https://github.com/Finschia/wasmd/pull/43
- feat: add admin-related events by @tkxkd0159 in https://github.com/Finschia/wasmd/pull/46
=> chore: bump up wasmd from v0.1.3 to v0.1.4

CHANGELOG.md, go.mod, go.sum
=> Feat: bump up finschia-sdk from v0.47.1-0.20230517010045-e9fe90608161 to v0.47.1-rc1

CHANGELOG.md, go.mod, go.sum
apply the changes of https://github.com/Finschia/finschia-sdk/pull/1019.
This is backport of https://github.com/Finschia/finschia-sdk/pull/1017.
=> feat: apply the changes of finschia-sdk#1019

.mergify.yml, CHANGELOG.md
closed: #212 
This change has been made by @zemyblue from Mergify config editor.
=> ci(Mergify): configuration update

CHANGELOG.md, go.mod, go.sum
Apply the next change of finschia-sdk v0.47.1-rc2
* Finschia/finschia-sdk#1026
* Finschia/finschia-sdk#1018
=> build: bump up finschia-sdk from v0.47.0 to v0.47.1-rc2

CHANGELOG.md, cli_test/cli_test.go, cli_test/test_helpers.go, go.mod, go.sum
This PR updates wasmd to a new version.
Containing a bug fix https://github.com/Finschia/wasmd/pull/57
=> build: update wasmd to v0.1.4+dynamiclink2 and go mod tidy

.github/workflows/check-generated.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, .github/workflows/tag.yml, .github/workflows/tests.yml, CHANGELOG.md, CONTRIBUTING.md, Dockerfile, README.md, docs/finschia-tutorials/installation.md, go.mod, networks/local/finschianode/Dockerfile
=> build: update golang version to 1.20

CHANGELOG.md, ante/ante_test.go, app/app.go, app/encoding.go, app/helpers/test_helpers.go, cli_test/cli_test.go, cli_test/multi_test.go, cli_test/test_helpers.go, cmd/fnsad/cmd/root.go, cmd/fnsad/cmd/testnet_test.go, cmd/fnsad/main.go, go.mod
=> Rename namespace to v2

.github/workflows/tests.yml, CHANGELOG.md, Makefile, app/app.go, contrib/check-upgrade-name.sh
This patch adds upgrade handler for `v2-Daisy` in-place migration.
=> feat: set upgrade handler for v2-Daisy

CHANGELOG.md, go.mod, go.sum
This patch would bump:
- github.com/Finschia/finschia-sdk from v0.47.2 to v0.47.3-0.20230817110929-1df6411c6429
- github.com/Finschia/wasmd from v0.1.3 to v0.1.5-0.20230818040015516eaaecf726
refer:
- Finschia/finschia-sdk#1061
- Finschia/finschia-sdk#1063
- Finschia/finschia-sdk#1075
- Finschia/finschia-sdk#1079
- Finschia/finschia-sdk#1066
- FInschia/finschia-sdk#1081
=> build: bump up several dependencies relevant to the event refactoring

.github/workflows/check-generated.yml, .github/workflows/ci-smart-contract.yml, .github/workflows/docker.yml, .github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, .github/workflows/tests.yml, CHANGELOG.md
closes: #XXXX
https://github.com/actions/checkout/compare/v3...v4
=> build(deps): bump actions/checkout from 3 to 4

CHANGELOG.md, go.mod, go.sum
bump up wasmd from v0.2.0 to v0.3.0.
* https://github.com/Finschia/cosmwasm/pull/343 ([CWA-2023-004 ](https://forum.cosmos.network/t/high-severity-security-patch-upcoming-on-wed-10th-cwa-2023-004-brought-to-you-by-certik-and-confio/12840))
* https://github.com/Finschia/cosmwasm/pull/344
* https://github.com/Finschia/wasmd/pull/118
=> feat!: bump up wasmd from v0.2.0 to v0.3.0

CHANGELOG.md, RELEASE_CHANGELOG.md, RELEASE_NOTE.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml, go.mod, go.sum
=> Release Finschia v2.0.2

CHANGELOG.md, go.mod, go.sum
closes: #XXXX
* fix fbridge auth bug
=> build(deps): bump `finschia-sdk` from v0.49.0-rc1 to v0.49.0-rc2

.github/workflows/check-generated.yml, CHANGELOG.md, ante/ante_test.go, app/app.go, app/encoding.go, app/helpers/test_helpers.go, cli_test/cli_test.go, cli_test/multi_test.go, cli_test/test_helpers.go, cmd/fnsad/cmd/root.go, cmd/fnsad/cmd/testnet_test.go, cmd/fnsad/main.go, go.mod, interchaintest/go.mod
This PR upgrades the app version to v4-Marigold.
=> feat: upgrade to v4

CHANGELOG.md, app/app.go, go.mod, go.sum
=> build(deps): bump `finschia-sdk` from v0.49.0-rc2 to v0.49.0-rc3

.gitignore, CHANGELOG.md
closes: #XXXX
goreleaser doesn't allow to modify git state during processing. So we need to add `RELEASE_NOTE.md` to `.gitignore`.
=> ci: add RELEASE_NOTE.md to .gitignore

CHANGELOG.md, app/app.go, go.mod, go.sum
=> bulid(deps): bump github.com/Finschia/finschia-sdk from v0.49.0-rc3 to v0.49.0-rc4

CHANGELOG.md, go.mod, go.sum
* bump finschis-sdk from v0.49.0-rc4 to v0.49.0-rc5
=> build: bump finschis-sdk from v0.49.0-rc4 to v0.49.0-rc5

CHANGELOG.md, app/app.go, client/docs/swagger-ui/swagger.yaml, go.mod, go.sum
* bump finschis-sdk from v0.49.0-rc5 to v0.49.0-rc6
=> build: bump up finschis-sdk from v0.49.0-rc5 to v0.49.0-rc6

CHANGELOG.md, client/docs/swagger-ui/swagger.yaml, go.mod, go.sum
=> build(deps): bump github.com/Finschia/finschia-sdk from v0.49.0-rc6 to v0.49.0-rc7

CHANGELOG.md, client/docs/config.json, client/docs/swagger-ui/swagger.yaml
=> Release Finschia v4.0.1
